### ISSUE TITLE
gss_export_cred produces the wrong form of token

### ISSUE THREAD

**Issue by jaltman** [PADL/mech_sanon#1]
Heimdal's commit b87b813feeadc21a510effee5421705445c7f44e ("sanon: Fix export/import_cred mismatch") must be implemented for MIT as well.

**Comment by lhoward** [comment]
Thanks Jeff, I’ll get onto it.

**Comment by lhoward** [comment]
Are you sure? MIT appears to do the OID tagging in the mechglue.

**Comment by jaltman** [comment]
@lhoward I submitted this based upon visual inspection.   The problem I was experiencing was likely due to #2 than the token format being wrong.
